[build-system]
requires = [
'joblib==1.1.0',
'kneed==0.7.0',
'matplotlib==3.5.0',
'numpy==1.21.4',
'pandas==1.3.4',  
'scikit-learn==0.24.2',
'scikit-optimize==0.9.0',
'scikit-plot==0.3.7',
'scipy==1.7.3',
'xgboost==1.5.0',

]
build-backend = "setuptools.build_meta"